### ISSUE TITLE
RStudio question

### ISSUE THREAD

**Issue by Wolflab** [pearselab/r-intro-Wolflab#4]
Will: I just noticed that I get different results whether I run source with or without echo. Unfortunately, I have been working with echo, which is obviously not correct (I checked by running from command line). Is this normal behavior for an IDE?

Paul
[source_no_echo.tiff.pdf](https://github.com/pearselab/r-intro-Wolflab/files/548583/source_no_echo.tiff.pdf)
[source_with_echo.tiff.pdf](https://github.com/pearselab/r-intro-Wolflab/files/548584/source_with_echo.tiff.pdf)

**Comment by willpearse** [comment]
I've not had this trouble before (probably one of the only benefits of emacs!). That said, I have heard of people running into trouble with source. I'd recommend doing whatever makes it look OK in RStudio for the time being - that's what I'll "mark" your answers in...

**Comment by willpearse** [comment]
Oh hang on, I know what's going on here and it's not a problem.

In the no echo version, because there's no newline at the end of your function, it plots the square immediately afterwards. If you just make your function `cat("\n")` at the end of it, it'll look the same in all cases. Nothing wrong with echo, and not really anything wrong with your function to be honest!

**Comment by Wolflab** [comment]
Oh - OK. That helps completely.  Thanks

**Comment by willpearse** [comment]
No worries!
